tasks:
  - name: Install npm-run-all and install all the projects dependencies
    init: npm install
    command: npm run install-all && gp sync-done install-all-task # The name 'install-all-task' is arbitrary

  - name: Start a project
    init: gp sync-await install-all-task # This will wait the install all task
    command: |
      cd react-intro-examples/SimpleReactElement
      npm run start
ports:
  - port: 3000 # The development web-server, must be public in order to test your app in your browser
    visibility: public
  - port: 3306 # The DB port, this must be private
    visibility: private
